# Generated by Django 6.0.4 on 2026-07-09 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_months', models.IntegerField()),
                ('benefits', models.TextField(help_text='Describe benefits, one per line or JSON')),
                ('max_courses', models.IntegerField(default=5, help_text='Number of courses accessible')),
                ('has_certificate', models.BooleanField(default=False)),
                ('has_mentoring', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Transfer Bank'), ('e_wallet', 'E-Wallet')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Berhasil', 'Berhasil'), ('Gagal', 'Gagal')], default='Pending', max_length=20)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='courses.course')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.subscriptionpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
